//! plan_card.rs
//! ------------
//! Renders a Plan (see protogen_plan::Plan) as an inline approve/reject
//! card in the chat log. Every step's `description` field is
//! deterministically generated by the daemon from the actual StepKind (see
//! plan-types/src/lib.rs describe()), never raw model text, so what's shown
//! here always matches exactly what will run if approved.
use gtk::prelude::*;
use gtk::{Box as GtkBox, Button, Label, Orientation};

use protogen_plan::Plan;

#[derive(Clone)]
pub struct PlanCard {
    container: GtkBox,
    pub approve_btn: Button,
    pub reject_btn: Button,
    pub plan_id: String,
}

impl PlanCard {
    pub fn new(plan: &Plan) -> Self {
        let container = GtkBox::new(Orientation::Vertical, 4);
        container.add_css_class("plan-card");

        let reply_label = Label::new(Some(&plan.reply));
        reply_label.set_wrap(true);
        reply_label.set_halign(gtk::Align::Start);
        container.append(&reply_label);

        let steps_box = GtkBox::new(Orientation::Vertical, 2);
        for step in &plan.steps {
            let l = Label::new(Some(&format!("• {}", step.description)));
            l.set_halign(gtk::Align::Start);
            l.add_css_class("plan-step");
            steps_box.append(&l);
        }
        container.append(&steps_box);

        let btn_row = GtkBox::new(Orientation::Horizontal, 6);
        let approve_btn = Button::with_label("Approve & Run");
        approve_btn.add_css_class("suggested-action");
        let reject_btn = Button::with_label("Cancel");
        btn_row.append(&approve_btn);
        btn_row.append(&reject_btn);
        container.append(&btn_row);

        Self { container, approve_btn, reject_btn, plan_id: plan.id.clone() }
    }

    pub fn widget(&self) -> &GtkBox {
        &self.container
    }

    pub fn disable_actions(&self) {
        self.approve_btn.set_sensitive(false);
        self.reject_btn.set_sensitive(false);
    }
}
